![NumPy](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1920px-NumPy_logo_2020.svg.png)

# Intro to NumPy and SciPy modules

**warning**: this notebook assumes that you are familiar with the basics of Python, if not you can look at the notebook Basics_of_python.ipynb.

**Credits**: parts of this notebook are based on examples and code of the Numpy warmup notebook of Tamás Gál (tamas.gal@fau.de) https://github.com/escape2020/school2022/blob/main/numpy/1_np_warm-up.ipynb

Python was not specifically designed for scientific computing (as opposed to matlab, R or Julia). Therefore, it does not now what a matrix or a vector is. NumPy implements these data structures with its `array` structure.

> NumPy is the building block of other scientific programming modules used for data analysis and machine learning: Pandas, scikit-learn, matplotlib.

Important take home messages :

 * Numpy is (almost) imported with alias `np`: `import numpy as np`.
 * Vectors of $\mathbb{R}^n$ are 1-D numpy arrays of shape `(n,)`.
 * `(n,)` and `(n,1)` arrays are **not** the same.
 * Matrices $\mathcal{M}^{n \times p}$ are 2-D numpy arrays of shape `(n,p)`.
 * **Frequent source of mistake**: forgetting to `copy()` an array when needed.
 * The `scipy` module is based on numpy and implements standard linear algebra tools, *e.g.* eigen decomposition, inversion, etc.

In [1]:
import numpy as np

rng = np.random.default_rng(seed = 42)

In [2]:
# IPython routine to display errors
from IPython.core.magic import register_line_magic

@register_line_magic
def shorterr(line):
    """Show only the exception message if one is raised."""
    try:
        output = eval(line)
    except Exception as e:
        print("\x1b[31m\x1b[1m{e.__class__.__name__}: {e}\x1b[0m".format(e=e))
    else:
        return output
    
del shorterr

## Building blocks of NumPy: the `ndarray`

#### Vectors (1D array)

In [3]:
x = np.array([1,2])
type(x)

numpy.ndarray

In [4]:
x

array([1, 2])

In [5]:
x.size # number of elts

2

In [6]:
x.ndim # number of axes (1 = vector, 2 = matrix, >=3 tensor)

1

In [7]:
x.shape

(2,)

#### Matrices (2D array)

In [8]:
A = np.array([[1,2,3], 
              [4,5,6]])
type(A)

numpy.ndarray

In [9]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
A.size

6

In [11]:
A.shape

(2, 3)

### ndrray vs list

In [12]:
x = [1, 2]
y = [i for i in range(3, 5)]
x + y # concatenation

[1, 2, 3, 4]

In [13]:
x = np.array(x)
y = np.array(y)
x + y # broadcasting (see below)

array([4, 6])

### Array Methods

In [14]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [15]:
x.min(), x.max(), x.mean(), x.sum()

(1, 6, 3.5, 21)

In [16]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
A.sum(axis=0) # sum overs 1st axis (rows)

array([5, 7, 9])

In [18]:
A.sum(axis=1) # sum over 2nd axis (columns)

array([ 6, 15])

## Indexing and slicing

In [19]:
x = np.arange(10) # equivalent to np.array(range(10))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[0] # indexing starts at 0

0

In [21]:
x[[0,4]] # you can give a list of index to subset

array([0, 4])

In [22]:
x[2:5] # tslice : ake all between 3rd and 6th (excluded)

array([2, 3, 4])

In [23]:
x[4:] # from 5th to last

array([4, 5, 6, 7, 8, 9])

In [24]:
x[:] # all values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[-1]  # -1 refers to the last element

9

In [26]:
x[2:6:3]  # just like in Python: [start:end:step]

array([2, 5])

In [27]:
x[::-1]  # reversing an array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Indexing and Slicing in Multiple Dimensions
Axis are separate by commas ","

In [28]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
A[0,0], A[0,2]

(1, 3)

In [30]:
A[:, 0] # select first column of A

array([1, 4])

In [31]:
A[0, :] # select first row of A

array([1, 2, 3])

In [32]:
%shorterr A[[0,2], [3,4]] # out of bounds indexes return error

IndexError: index 2 is out of bounds for axis 0 with size 2


In [33]:
A[::-1, ::-1]  # reverses both axes

array([[6, 5, 4],
       [3, 2, 1]])

#### Advanced Indexing



In [34]:
d = np.array([4, 3, 2, 5, 4, 5, 4, 4])

In [35]:
mask = np.array([True, False, False, True, False, False, True, True])
mask

array([ True, False, False,  True, False, False,  True,  True])

In [36]:
d[mask]

array([4, 5, 4, 4])

In [37]:
d[[1, 3, 1, 6]]

array([3, 5, 3, 4])

##### Be careful with boolean indexing, the mask has to be a boolean array or a list of booleans.

In [38]:
d[[0, 1, 0, 0, 1, 0, 0, 1]]  # although we know that True==1 and False==0

array([4, 3, 4, 4, 3, 4, 4, 3])

## Helper Functions to Create Arrays

In [39]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [40]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [41]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros(shape = (2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.eye(5) # diag matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.linspace(1, 2, 10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [45]:
np.ones_like(x) # create an array of 1 with same shape as x

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Maths with NumPy arrays

### Operations: +, `*`, `**`, `==` done elementwise.

In [46]:
x = np.array([i for i in range(10)])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
x + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
x ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [50]:
x / np.pi - 7

array([-7.        , -6.68169011, -6.36338023, -6.04507034, -5.72676046,
       -5.40845057, -5.09014068, -4.7718308 , -4.45352091, -4.13521102])

In [51]:
x == 5 

array([False, False, False, False, False,  True, False, False, False,
       False])

In [52]:
np.sum(x > 2) # number of elts > 2 in x

7

In [53]:
(x > 3) & (x < 5)  # bitwise AND

array([False, False, False, False,  True, False, False, False, False,
       False])

### Broadcasting

##### if the shapes match, operations are usually done element-by-element

In [54]:
print(x + x)
print(x * x)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]


In [55]:
g = np.array([1, 2, 3, 4])
h = np.array([5, 6, 7, 8])
g * h  

array([ 5, 12, 21, 32])

In [56]:
g * 23  # as we have already seen, the rule relaxes when the shapes meet certain constraints

array([23, 46, 69, 92])

### Broadcasting rules
- NumPy compares the shapes element-wise, starting with the trailing dimension
- two dimensions are compatible if they are equal or one of them is __1__
- raises a `ValueError: frames are not aligned` if the shapes are incompatible
- the size of a successfully broadcasted array is the maximum size along each dimension of the input arrays

In [57]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[1], [2]])

print('arr_1 shape:', arr_1.shape)
print('arr_2 shape:', arr_2.shape)

arr_3 = arr_1 + arr_2
print('arr_3 shape:', arr_3.shape)

arr_3

arr_1 shape: (2, 3)
arr_2 shape: (2, 1)
arr_3 shape: (2, 3)


array([[2, 3, 4],
       [6, 7, 8]])

In [58]:
i = np.arange(20).reshape(4, 5)
i

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
j = np.array([0, 10, 20, 30])
k = np.array([7, 8, 9])

In [60]:
%shorterr j+k

ValueError: operands could not be broadcast together with shapes (4,) (3,) 


In [61]:
j[:, np.newaxis]  # inserts a new axis, making it two dimensional

array([[ 0],
       [10],
       [20],
       [30]])

In [62]:
j[:, np.newaxis] + k

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29],
       [37, 38, 39]])

## Universal Functions (`ufunc`)

#### A `ufunc` is a "vectorized" wrapper for a function that takes a fixed number of scalar inputs and produces a fixed number of scalar outputs.

NumPy provides a bunch of `ufunc`s:
- Math operations (`add()`, `subtract()`, `square()`, `log10()`, ...)
- Trigonometric functions (`sin()`, `cos()`, `tan()`, `deg2rad()`, ...)
- Bit-twiddling functions (`bitwise_and()`, `right_shift()`, ...)
- Comparison functions (`greater()`, `less_equal()`, `fmax()`, ...)
- Floating functions (`isnan()`, `isinf()`, `floor()`, ...)
    
They all are subclasses of `np.ufunc`

In [63]:
type(np.cos)  # they all are subclasses of np.ufunc

numpy.ufunc

In [64]:
np.cos(x) # vectorized function

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

## Linear algebra

Matrix multiplication is done via the `@` operator or the `np.dot()` function.

* $y = Ax$ 
* $\langle x, y \rangle = x^\top y$

In [65]:
p = 5
x = rng.normal(size = (p,)) # 
y = rng.normal(size = (p,))
x.dot(y) # x^T y

0.8814431885547835

In [66]:
np.inner(x, y) # alternative

0.8814431885547835

In [67]:
p = 5
n = 8
A = rng.normal(size = (n, p))
A

array([[ 0.87939797,  0.77779194,  0.0660307 ,  1.12724121,  0.46750934],
       [-0.85929246,  0.36875078, -0.9588826 ,  0.8784503 , -0.04992591],
       [-0.18486236, -0.68092954,  1.22254134, -0.15452948, -0.42832782],
       [-0.35213355,  0.53230919,  0.36544406,  0.41273261,  0.430821  ],
       [ 2.1416476 , -0.40641502, -0.51224273, -0.81377273,  0.61597942],
       [ 1.12897229, -0.11394746, -0.84015648, -0.82448122,  0.65059279],
       [ 0.74325417,  0.54315427, -0.66550971,  0.23216132,  0.11668581],
       [ 0.2186886 ,  0.87142878,  0.22359555,  0.67891356,  0.06757907]])

In [68]:
y = A @ x # y = Ax 
y 

array([-0.34325472, -0.44128407,  2.25962047, -0.83899147, -1.27635485,
       -2.21278311, -0.84711749, -0.16512338])

In [69]:
y.shape

(8,)

In [70]:
np.alltrue(A.dot(x) == A @ x) # A.dot is for python <= 3.5

True

In [71]:
%shorterr x @ A # shape do not match

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 8 is different from 5)


### Random numbers generation

In [72]:
rng = np.random.default_rng(42)  # always create a generator with a seed! => reproducibility

In [73]:
rng.random((3, 4)) # Unif([0,1])

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [74]:
rng.uniform(0, 5, 10) # Unif([0,5])

array([3.2193256 , 4.11380807, 2.21707099, 1.13619361, 2.77292394,
       0.31908628, 4.13815586, 3.158322  , 3.7904387 , 1.77262984])

In [75]:
rng.integers(1, 10, (2, 20)) # discrete uniform of {1, ..., 10}

array([[1, 9, 5, 9, 7, 8, 7, 2, 4, 5, 5, 1, 5, 2, 7, 7, 9, 7, 4, 9],
       [4, 3, 9, 4, 1, 5, 8, 2, 5, 2, 7, 5, 3, 3, 6, 7, 9, 4, 2, 8]])

In [76]:
rng.normal(loc = 0, scale = 1, size = (3, 4)) # N(loc, scale)

array([[-1.17119517,  0.54315427, -0.66550971,  0.23216132],
       [ 0.11668581,  0.2186886 ,  0.87142878,  0.22359555],
       [ 0.67891356,  0.06757907,  0.2891194 ,  0.63128823]])